[26-Nov-2017 11:02:18 Europe/Berlin] Uncaught exception: </p>Exception with message Controller class App\Controllers\Jasiu not found\nStack trace:#0 C:\xampp\htdocs\mvc2\public\index.php(41): Core\Router->dispatch('jasiu/talk')
#1 {main}Throw in: C:\xampp\htdocs\mvc2\Core\Router.php on line 173
[26-Nov-2017 11:02:31 Europe/Berlin] Uncaught exception: </p>Exception with message No route matched\nStack trace:#0 C:\xampp\htdocs\mvc2\public\index.php(41): Core\Router->dispatch('jasiu')
#1 {main}Throw in: C:\xampp\htdocs\mvc2\Core\Router.php on line 176
[26-Nov-2017 11:02:38 Europe/Berlin] Uncaught exception: </p>Exception with message No route matched\nStack trace:#0 C:\xampp\htdocs\mvc2\public\index.php(41): Core\Router->dispatch('logind')
#1 {main}Throw in: C:\xampp\htdocs\mvc2\Core\Router.php on line 176
[26-Nov-2017 16:16:55 Europe/Berlin] Uncaught exception: </p>PDOException with message SQLSTATE[HY000] [1049] Unknown database 'mvc_3'\nStack trace:#0 C:\xampp\htdocs\mvc\Core\Model.php(20): PDO->__construct('mysql:host=loca...', 'root', '')
#1 C:\xampp\htdocs\mvc\App\Models\User.php(154): Core\Model::getDB()
#2 C:\xampp\htdocs\mvc\App\Auth.php(93): App\Models\User::findById('22')
#3 C:\xampp\htdocs\mvc\Core\View.php(41): App\Auth::getUser()
#4 C:\xampp\htdocs\mvc\Core\View.php(29): Core\View::getTemplate('/Home/index.htm...', Array)
#5 C:\xampp\htdocs\mvc\App\Controllers\Home.php(16): Core\View::renderTemplate('/Home/index.htm...')
#6 [internal function]: App\Controllers\Home->indexAction(Array)
#7 C:\xampp\htdocs\mvc\Core\Controller.php(26): call_user_func(Array, Array)
#8 C:\xampp\htdocs\mvc\Core\Router.php(168): Core\Controller->__call('index', Array)
#9 C:\xampp\htdocs\mvc\public\index.php(42): Core\Router->dispatch('')
#10 {main}Throw in: C:\xampp\htdocs\mvc\Core\Model.php on line 20
[26-Nov-2017 16:16:56 Europe/Berlin] Uncaught exception: </p>PDOException with message SQLSTATE[HY000] [1049] Unknown database 'mvc_3'\nStack trace:#0 C:\xampp\htdocs\mvc\Core\Model.php(20): PDO->__construct('mysql:host=loca...', 'root', '')
#1 C:\xampp\htdocs\mvc\App\Models\User.php(154): Core\Model::getDB()
#2 C:\xampp\htdocs\mvc\App\Auth.php(93): App\Models\User::findById('22')
#3 C:\xampp\htdocs\mvc\Core\View.php(41): App\Auth::getUser()
#4 C:\xampp\htdocs\mvc\Core\View.php(29): Core\View::getTemplate('/Home/index.htm...', Array)
#5 C:\xampp\htdocs\mvc\App\Controllers\Home.php(16): Core\View::renderTemplate('/Home/index.htm...')
#6 [internal function]: App\Controllers\Home->indexAction(Array)
#7 C:\xampp\htdocs\mvc\Core\Controller.php(26): call_user_func(Array, Array)
#8 C:\xampp\htdocs\mvc\Core\Router.php(168): Core\Controller->__call('index', Array)
#9 C:\xampp\htdocs\mvc\public\index.php(42): Core\Router->dispatch('')
#10 {main}Throw in: C:\xampp\htdocs\mvc\Core\Model.php on line 20
[26-Nov-2017 16:16:56 Europe/Berlin] Uncaught exception: </p>PDOException with message SQLSTATE[HY000] [1049] Unknown database 'mvc_3'\nStack trace:#0 C:\xampp\htdocs\mvc\Core\Model.php(20): PDO->__construct('mysql:host=loca...', 'root', '')
#1 C:\xampp\htdocs\mvc\App\Models\User.php(154): Core\Model::getDB()
#2 C:\xampp\htdocs\mvc\App\Auth.php(93): App\Models\User::findById('22')
#3 C:\xampp\htdocs\mvc\Core\View.php(41): App\Auth::getUser()
#4 C:\xampp\htdocs\mvc\Core\View.php(29): Core\View::getTemplate('/Home/index.htm...', Array)
#5 C:\xampp\htdocs\mvc\App\Controllers\Home.php(16): Core\View::renderTemplate('/Home/index.htm...')
#6 [internal function]: App\Controllers\Home->indexAction(Array)
#7 C:\xampp\htdocs\mvc\Core\Controller.php(26): call_user_func(Array, Array)
#8 C:\xampp\htdocs\mvc\Core\Router.php(168): Core\Controller->__call('index', Array)
#9 C:\xampp\htdocs\mvc\public\index.php(42): Core\Router->dispatch('')
#10 {main}Throw in: C:\xampp\htdocs\mvc\Core\Model.php on line 20
[26-Nov-2017 16:17:50 Europe/Berlin] Uncaught exception: </p>PDOException with message SQLSTATE[HY000] [1049] Unknown database 'mvc_3'\nStack trace:#0 C:\xampp\htdocs\mvc\Core\Model.php(20): PDO->__construct('mysql:host=loca...', 'root', '')
#1 C:\xampp\htdocs\mvc\App\Models\User.php(154): Core\Model::getDB()
#2 C:\xampp\htdocs\mvc\App\Auth.php(93): App\Models\User::findById('22')
#3 C:\xampp\htdocs\mvc\Core\View.php(41): App\Auth::getUser()
#4 C:\xampp\htdocs\mvc\Core\View.php(29): Core\View::getTemplate('/Home/index.htm...', Array)
#5 C:\xampp\htdocs\mvc\App\Controllers\Home.php(16): Core\View::renderTemplate('/Home/index.htm...')
#6 [internal function]: App\Controllers\Home->indexAction(Array)
#7 C:\xampp\htdocs\mvc\Core\Controller.php(26): call_user_func(Array, Array)
#8 C:\xampp\htdocs\mvc\Core\Router.php(168): Core\Controller->__call('index', Array)
#9 C:\xampp\htdocs\mvc\public\index.php(42): Core\Router->dispatch('')
#10 {main}Throw in: C:\xampp\htdocs\mvc\Core\Model.php on line 20
[26-Nov-2017 16:17:50 Europe/Berlin] Uncaught exception: </p>PDOException with message SQLSTATE[HY000] [1049] Unknown database 'mvc_3'\nStack trace:#0 C:\xampp\htdocs\mvc\Core\Model.php(20): PDO->__construct('mysql:host=loca...', 'root', '')
#1 C:\xampp\htdocs\mvc\App\Models\User.php(154): Core\Model::getDB()
#2 C:\xampp\htdocs\mvc\App\Auth.php(93): App\Models\User::findById('22')
#3 C:\xampp\htdocs\mvc\Core\View.php(41): App\Auth::getUser()
#4 C:\xampp\htdocs\mvc\Core\View.php(29): Core\View::getTemplate('/Home/index.htm...', Array)
#5 C:\xampp\htdocs\mvc\App\Controllers\Home.php(16): Core\View::renderTemplate('/Home/index.htm...')
#6 [internal function]: App\Controllers\Home->indexAction(Array)
#7 C:\xampp\htdocs\mvc\Core\Controller.php(26): call_user_func(Array, Array)
#8 C:\xampp\htdocs\mvc\Core\Router.php(168): Core\Controller->__call('index', Array)
#9 C:\xampp\htdocs\mvc\public\index.php(42): Core\Router->dispatch('')
#10 {main}Throw in: C:\xampp\htdocs\mvc\Core\Model.php on line 20
[26-Nov-2017 16:17:50 Europe/Berlin] Uncaught exception: </p>PDOException with message SQLSTATE[HY000] [1049] Unknown database 'mvc_3'\nStack trace:#0 C:\xampp\htdocs\mvc\Core\Model.php(20): PDO->__construct('mysql:host=loca...', 'root', '')
#1 C:\xampp\htdocs\mvc\App\Models\User.php(154): Core\Model::getDB()
#2 C:\xampp\htdocs\mvc\App\Auth.php(93): App\Models\User::findById('22')
#3 C:\xampp\htdocs\mvc\Core\View.php(41): App\Auth::getUser()
#4 C:\xampp\htdocs\mvc\Core\View.php(29): Core\View::getTemplate('/Home/index.htm...', Array)
#5 C:\xampp\htdocs\mvc\App\Controllers\Home.php(16): Core\View::renderTemplate('/Home/index.htm...')
#6 [internal function]: App\Controllers\Home->indexAction(Array)
#7 C:\xampp\htdocs\mvc\Core\Controller.php(26): call_user_func(Array, Array)
#8 C:\xampp\htdocs\mvc\Core\Router.php(168): Core\Controller->__call('index', Array)
#9 C:\xampp\htdocs\mvc\public\index.php(42): Core\Router->dispatch('')
#10 {main}Throw in: C:\xampp\htdocs\mvc\Core\Model.php on line 20
